department_codes = {
    'ANT': 'Antioquia',
    'ATL': 'Atlántico',
    'BOL': 'Bolívar',
    'BOY': 'Boyacá',
    'CAL': 'Caldas',
    'CHO': 'Chocó',
    'COR': 'Córdoba',
    'RIS': 'Risaralda',
    'SAN': 'Santander',
    'SUC': 'Sucre'
}

{
'AND': 'Andes',
'ANS': 'Anserma',
'APA': 'Apartadó',
'API': 'Apía',
'AYA': 'Ayapel',
'BAR': 'Barbosa',
'BBE': 'Barrancabermeja',
'BDL': 'Barranco de Loba',
'BAQ': 'Barranquilla',
'BEL': 'Belalcázar',
'BEN': 'Belén',
'BEO': 'Bello',
'BOJ': 'Bojayá(Bellavista)',
'BOL': 'Bolívar',
'BUC': 'Bucaramanga',
'BUE': 'Buenavista',
'CAC': 'Cáceres',
'CAL': 'Calamar',
'CAN': 'Candelaria',
'CAG': 'Cañasgordas',
'CAR': 'Carepa',
'CTG': 'Cartagena',
'CAU': 'Caucasia',
'CHI': 'Chigorodó',
'CHM': 'Chimá',
'CHN': 'Chinchiná',
'CHU': 'Chinu',
'CHQ': 'Chiquinquirá',
'CHZ': 'Chiquiza',
'CHT': 'Chita',
'CDO': 'Cienaga De Oro',
'COL': 'Colosó',
'COM': 'Cómbita',
'CON': 'Condoto',
'COR': 'Córdoba',
'COZ': 'Corozal',
'CUR': 'Curití',
'DAB': 'Dabeiba',
'DOS': 'Dos Quebradas',
'DUI': 'Duitama',
'ELB': 'El Bagre',
'ECB': 'El Carmen de Bolívar',
'EES': 'El Espino',
'EPL': 'El Playón',
'ENV': 'Envigado',
'FLO': 'Floridablanca',
'GAL': 'Galapa',
'GIR': 'Girón',
'GUA': 'Guayatá',
'ITU': 'Ituango',
'JEN': 'Jenesano',
'JDA': 'Juan de Acosta',
'LME': 'La Merced',
'LVI': 'La Virginia',
'LSJ': 'Litoral de San Juan',
'LOR': 'Lorica',
'LCO': 'Los Córdobas',
'LPA': 'Los Palmitos',
'LUR': 'Luruaco',
'MAG': 'Magangué',
'MAL': 'Malambo',
'MAN': 'Manizales',
'MAR': 'Margarita',
'MLB': 'María la Baja',
'MED': 'Medellín',
'MIS': 'Mistrató',
'MON': 'Monguí',
'MTE': 'Montería',
'MOR': 'Morroa',
'NEC': 'Necoclí',
'NBB': 'Nuevo Belén de Bajirá',
'NCO': 'Nuevo Colón',
'OVE': 'Ovejas',
'PAC': 'Pácora',
'PAJ': 'Pajarito',
'PAL': 'Palmito',
'PAN': 'Panqueba',
'PER': 'Pereira',
'PIE': 'Piedecuesta',
'PIN': 'Pinchote',
'PRI': 'Planeta Rica',
'PTN': 'Pto Nare(La Magdalena)',
'PNU': 'Pueblo Nuevo',
'PRC': 'Pueblo Rico',
'PES': 'Puerto Escondido',
'PLI': 'Puerto Libertador',
'PUR': 'Purísima',
'QUI': 'Quibdó',
'RQT': 'Río Quito',
'RIN': 'Rionegro',
'RIS': 'Riosucio',
'SAG': 'Sabanagrande',
'SAL': 'Sabanalarga',
'SAN': 'Sabaneta',
'SAH': 'Sahagún',
'SLG': 'Salgar',
'SAM': 'Samaná',
'SPU': 'Sampues',
'SAD': 'San Andrés',
'SBA': 'San Benito Abad',
'SGI': 'San Gil',
'SJA': 'San Jacinto',
'SJU': 'San José de Uré',
'SJP': 'San José del Palmar',
'SJN': 'San Juan Nepomuceno',
'SLS': 'San Luis De Sincé',
'SML': 'San Martín de Loba',
'SPA': 'San Pablo',
'SPE': 'San Pedro de Urabá',
'SPL': 'San Pelayo',
'SAR': 'Santa Rosa',
'SRO': 'Santa Rosa de Osos',
'STO': 'Santo Tomás',
'SAT': 'Sativasur',
'SIN': 'Sincelejo',
'SOC': 'Socorro',
'SOT': 'Socotá',
'SOL': 'Soledad',
'SQA': 'Sotaquirá',
'SUA': 'Suaita',
'SUP': 'Supía',
'TAD': 'Tadó',
'TAM': 'Támesis',
'TIB': 'Tibaná',
'TIE': 'Tierralta',
'TUB': 'Tubará',
'TUR': 'Turbaco', 
'TUA': 'Turbaná',
'TUO': 'Turbo',    
'UNG': 'Unguía',
'VAL': 'Valencia',
'YAR': 'Yarumal',
'ZAM': 'Zambrano',
'ZAR': 'Zaragoza'
}
